### PR TITLE
Madhura core ap is

### PR DESCRIPTION
**Pull request by madhura-kulkarni-mh**
@rizdaprasetya I have commited three files- Overview, Bank transfer and e-Wallet file from CoreAPIs for your review. Kindly go through them.

### CODE REVIEW

**Comment by madhura-kulkarni-mh** [comment]
@rizdaprasetya I have pushed Overview file, Bank transfer file and e-Wallet file from Core APIs for your review. Kindly go through them.

**Comment by rizdaprasetya** [comment]
@madhura-kulkarni-mh why do you create another PR? This PR also still mix Snap & Core API submission, it does not just address Core API. As [I already explained here](https://github.com/Midtrans/technical-documentation-site/pull/32#issuecomment-730833097), please continue work there for both Snap & Core API. So Please add this Core API changes to [that PR](https://github.com/Midtrans/technical-documentation-site/pull/32). I will only review 1 PR for both your Snap & Core API, which [is that PR](https://github.com/Midtrans/technical-documentation-site/pull/32).

I will close this PR, as this is confusing.

**Comment by madhura-kulkarni-mh** [comment]
Hi Rizda,
Can we have a quick call to discuss this issue?

**Comment by rizdaprasetya** [comment]
Closing this PR, because it already [consolidated here](https://github.com/Midtrans/technical-documentation-site/pull/32#commitcomment-44704608)

**Pull request closed without merging**
