### PR TITLE
Update tech docs Snap screenshot/image from old Snap with new Snap

### PR DESCRIPTION
**Pull request by Andrenzo17**

### CODE REVIEW

**Comment by rizdaprasetya** [comment]
haven't thoroughly review all, but here's a suggestion @Andrenzo17 :
- please compress/optimize the image size using this tool https://kraken.io/web-interface (try using default config for optimal image size), but please also ensure the image still looks good.

Thanks.

**Comment by rizdaprasetya** [comment]
haven't thoroughly review all, but here's a suggestion @Andrenzo17 :
- please compress/optimize the image size using this tool https://kraken.io/web-interface (try using default config for optimal image size), but please also ensure the image still looks good.

Thanks.

**Comment by Andrenzo17** [comment]
Noted kak, will try optimize the image size
Thank you

**Review by Xaxxis — CHANGES_REQUESTED** [review]
The image resolution is too big. Please resize to W: 434px | H: 654px @Andrenzo17

**Comment by Andrenzo17** [comment]
Notes zak, will revise the size

**Comment by Xaxxis** [comment]
Just minor feedback feel free to take it or not ya, it might be more eye-catching if you set the Snap color theme with the same docs.midtrans.com color.

**Review by Xaxxis — CHANGES_REQUESTED** [review]
@Andrenzo17 Sorry I missed this one. this image should be the card details that have already been saved and previewed on the Snap card payment page, for future transactions

https://github.com/Midtrans/technical-documentation-site/pull/77/commits/b36dd7ef007459a680812472ce60daeaac69c7fc

**Comment by Andrenzo17** [comment]
Hi Zak thanks for feedback, i miss to read this line too `Their card will be previewed on Snap card payment page, on future transactions.`

Will revise ASAP. Thank tou

**Review by Xaxxis — APPROVED** [review]

**Comment by Xaxxis** [comment]
Looks good to me! @Andrenzo17

**Review by rizdaprasetya — CHANGES_REQUESTED** [review]
[asset/image/snap-popup-preview.gif](https://github.com/Midtrans/technical-documentation-site/pull/77/files?short_path=6a242b0#diff-518fd5c02e22d5aee968b8ca46c998f47dcb1457ced584d0c2790bcbb21d11d0)

Why don't you scroll down and up to show all payment method like the original gif?

[asset/image/snap-test-transaction.gif](https://github.com/Midtrans/technical-documentation-site/pull/77/files?short_path=6a242b0#diff-6a242b001f2a20e02bf9d10dfaf3a90a968f2f3b80c266c2398f309073e5046e)

You added an extra step compared to the original gif. By opening QRIS image in new tab & copying the url, you are making it looks more compliated, why not just right click and copy the address?

Please improve @Andrenzo17 . Thanks

Thanks @Xaxxis  for the help in reviewing.

**Comment by Andrenzo17** [comment]
Thank you for feedback kak @rizdaprasetya 
kindly help to review again

**Review by rizdaprasetya — APPROVED** [review]
Ok, looks good now, I'll merge.
Note: will merge-squash (into 1 merge commit) to reduce unnecessary commits number & file changes.

Please announce release on our slack release channel @Andrenzo17

**Pull request merged**
